---

apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  manageNodes: false
  monPVCTemplate:
    spec:
      storageClassName: gp2
      accessModes:
        - ReadWriteOnce
  resources:
    mds:
      limits:
        cpu: 3000m
        memory: 8Gi
      requests:
        cpu: 1000m
        memory: 8Gi
    mgr:
      limits:
        cpu: 1000m
        memory: 3Gi
      requests:
        cpu: 1000m
        memory: 3Gi
    mon:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 1000m
        memory: 2Gi
  storageDeviceSets:
    - name: mydeviceset
      count: STORAGE_NODES
      dataPVCTemplate:
        spec:
          storageClassName: gp2
          accessModes:
            - ReadWriteOnce
          volumeMode: Block
          resources:
            requests:
              storage: 1000Gi
      placement: {}
      portable: true
      resources:
        limits:
          cpu: 2000m
          memory: 5Gi
        requests:
          cpu: 1000m
          memory: 5Gi
  multiCloudGateway:
    reconcileStrategy: "ignore"
